### ISSUE TITLE
[feature request] Preview image size according to media adjustments

### ISSUE THREAD

**Issue by Pjirlip** [jweiland-net/video_shariff#12]
Hallo, 

erstmal vielen Dank für das kleine Plugin an das JWeiland-Team. Funktioniert ohne Problem, ich hätte aber noch einen Feature Request. 

Wenn man für das Videoelement eine Breite und/oder Höhe einstellt nimmt der Preview-Container trotzdem die volle Breite seines Parent-Containers ein und erst nachdem man mit Klick zugestimmt hat, wird das Videoelement in der korrekt festgelegten Dimension dargestellt. 

Es wäre meiner Meinung nach sinnvoll, wenn auch der Preview-Container die festgelegten Werte für Breite/Höhe des Media-Elements übernimmt, falls diese gesetzt sind.

Mit freundlichen Grüßen, 
PD

**Comment by pascal20997** [comment]
Hallo Philipp,

das Vorschaubild sollte im Normalfall die Größeneinstellung übernehmen. Das ganze wird über den f:image ViewHelper geregelt:
`<f:image src="{previewImage}" width="{dimensions.width}" height="{dimensions.height}"/>`

Lokal hatte ich mal ein Pfadproblem mit ddev. Die ImageMagick Komponenten liegen dort unter /usr/bin, während bei mir noch /usr/local/bin eingestellt waren und TYPO3 dann ohne Fehlermeldung einfach das Originalbild mit Originalgröße ausgegeben hat.

Kannst du mal im Quellcode schauen ob dein Vorschaubild unter `typo3temp/assets/_processed_` liegt?

**Comment by Pjirlip** [comment]
Hallo Pascal, 

vielen Dank für deine schnelle Rückmeldung, 
ImageMagick ist verfügbar und das Bild wird korrekt aus _processed_ referenziert. 

![Bildschirmfoto 2019-10-28 um 15 41 28](https://user-images.githubusercontent.com/9822378/67688009-73d28600-f999-11e9-8209-95f68b73bbe3.png)

Bei weiteren Versuchen ist mir aufgefallen, dass nur `dimensions.width` den Wert "falsch" setzt. Die Höhe wird korrekt ausgegeben. Weiter ist mir dann aufgefallen, dass er die Breite an die Höhe anpasst, scheinbar um das Verhältnis gleich zu behalten. Ich gehe stark davon aus, dass das Verhalten so gewollt ist. Dementsprechend kann das Issue geschlossen werden. Vielen Dank nochmal für deine Rückmeldung.
