### ISSUE TITLE
Open videos in a lightbox if "Click enlarge" is set in the CE

### ISSUE THREAD

**Issue by wowaTYPO3** [jweiland-net/video_shariff#20]
Maybe a nice feature: 
if you set the "Click enlarge"-checkbox in the "Text & Media"-CE, the videos could be played in a lightbox. Otherwise, if the checkbox is deactivated, the behaviour could be the same as it is now.

The settings for the lightbox rendering of fluid_styled_content would have to be taken into account.

Note: The rendering can be changed with
lib.contentElement.settings.media.popup {
  linkParams.ATagParams.dataWrap =  data-fancybox="gallery[{file:current:uid_foreign}]" data-caption="{file:current:title}" class="{$styles.content.textmedia.linkWrap.lightboxCssClass}" rel="{$styles.content.textmedia.linkWrap.lightboxRelAttribute}"
}

**Comment by froemken** [comment]
Hello @wowaTYPO3 

this is of cause a pretty cool idea and IMO that should be solved in TYPO3 core itself. video_shariff is an extension to just add the overlay to a video. It does not manage content rendering and IMO it should never touch content rendering.

Maybe it's better to add such a feature request to forge.typo3.org

Have a cool start into this weekend

Stefan
