### ISSUE TITLE
Clear name for the category in the constant editor

### ISSUE THREAD

**Issue by wowaTYPO3** [jweiland-net/video_shariff#21]
At the moment the category is only called "Basic". So you can't see at first sight that it belongs to the extension.

![2020-06-23_14-46-19](https://user-images.githubusercontent.com/343511/85405410-a9e3fc00-b560-11ea-8307-a588ad38ced4.png)

**Comment by pascal20997** [comment]
Hey Wolfang, you are right. I'll change that to lib.video_shariff within the next release
