### ISSUE TITLE
Error thrown in JavaScript due to Typo3 adding "noicon"-class 

### ISSUE THREAD

**Issue by uzerterter** [jweiland-net/video_shariff#30]
When i installed and tested the extension the `while (previewLink.className !== 'video-shariff-play')` check failed to stop at the correct element due to Typo3 adding a "noicon"-class to the "video-shariff-play"-element. 
I wrote a small patch to prevent that from happening: 
`while (!previewLink.className.split(' ').includes('video-shariff-play'))`
I think this should still work the intended way while being less error-prone.

**Comment by froemken** [comment]
Hello @uzerterter 

thank you to make video_shariff a better extension.
I have adopted your patch into version 2.0.2 which was just released for composer at packagist. I will release version 2.0.2 to TER at monday, too.

Have a nice evening

Stefan
