### ISSUE TITLE
Video-Shariff conflicts with facebook SDK

### ISSUE THREAD

**Issue by stephangrass** [jweiland-net/video_shariff#32]
When I try to load the Facebook SDK on a system that also has Video Shariff loaded, I get the error

`Uncaught SyntaxError: redeclaration of let i`

in the Facebook sdk.js

I load the sdk.js after all other scripts, so the VideoShariff.js is causing the error because i is already declared globally there.

**Comment by froemken** [comment]
Hello @stephangrass 

thank you for your help. I just found a PR which solves this issue and merged it.
I have released version 2.0.1 for Composer to Packagist. I hope I will find time to upload this release to TER on monday.

Have a nice weekend

Stefan
