### ISSUE TITLE
shariff dont works with tx_news.

### ISSUE THREAD

**Issue by typo3max** [jweiland-net/video_shariff#48]
maybe a little bug. Newest TYPO3 12, and tx_news.

Thank you

**Comment by typo3max** [comment]
sry, maybe its a T3Ui-Kit Bug.

**Comment by hojalatheef** [comment]
Hi @typo3max 

Thanks a lot for reporting this issue! I tested this on a TYPO3 12 instance with tx_news and other content elements, but I couldn’t reproduce the issue.

Could you please double-check if the TypoScript static configuration template for video_shariff is added? Also, it might help to check if JavaScript compression settings are causing any conflicts. Lastly, please look at the browser console for any additional errors that could point us in the right direction.

Thank you again for helping improve the project!

**Comment by typo3max** [comment]
Dosnt matter its a t3uikit issue, thanks a lot
